### ISSUE TITLE
Cannot find the manifest

### ISSUE THREAD

**Issue by methatronc** [jellyfin/jellyfin-plugin-sessioncleaner#7]
Hello,

I used https://repo.codyrobibero.dev/manifest.json for the manifest but I get a 403 error in the jellyfin logs when it loads the manifests.
Indeed when checking the url it says the dns record is not right, has the manifest url changed ?

Thanks for your help

**Comment by crobibero** [comment]
My repo doesn't exist anymore. 
This plugin will be in the main plugin repo when 10.8 is released

**Comment by methatronc** [comment]
Great, congrats ! :)
